### PR TITLE
AzureAOAIに対応

### PR DESCRIPTION
**Pull request by BC-YAMAMOTO-IKU**

### CODE REVIEW

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
test this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by yamamoto-iku** [comment]
reivew this please

**Comment by yamamoto-iku** [comment]
review this please

**Comment by BC-YAMAMOTO-IKU** [comment]
review this please

**Pull request merged**
